// Code generated by protoc-gen-micro. DO NOT EDIT.
// source: hello.proto

package hello

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

import (
	context "context"
	client "github.com/micro/go-micro/client"
	server "github.com/micro/go-micro/server"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ client.Option
var _ server.Option

// Client API for SrvTwo service

type SrvTwoService interface {
	Hello(ctx context.Context, in *HelloRequest, opts ...client.CallOption) (*HelloResponse, error)
}

type srvTwoService struct {
	c    client.Client
	name string
}

func NewSrvTwoService(name string, c client.Client) SrvTwoService {
	if c == nil {
		c = client.NewClient()
	}
	if len(name) == 0 {
		name = "srvtwo"
	}
	return &srvTwoService{
		c:    c,
		name: name,
	}
}

func (c *srvTwoService) Hello(ctx context.Context, in *HelloRequest, opts ...client.CallOption) (*HelloResponse, error) {
	req := c.c.NewRequest(c.name, "SrvTwo.Hello", in)
	out := new(HelloResponse)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for SrvTwo service

type SrvTwoHandler interface {
	Hello(context.Context, *HelloRequest, *HelloResponse) error
}

func RegisterSrvTwoHandler(s server.Server, hdlr SrvTwoHandler, opts ...server.HandlerOption) error {
	type srvTwo interface {
		Hello(ctx context.Context, in *HelloRequest, out *HelloResponse) error
	}
	type SrvTwo struct {
		srvTwo
	}
	h := &srvTwoHandler{hdlr}
	return s.Handle(s.NewHandler(&SrvTwo{h}, opts...))
}

type srvTwoHandler struct {
	SrvTwoHandler
}

func (h *srvTwoHandler) Hello(ctx context.Context, in *HelloRequest, out *HelloResponse) error {
	return h.SrvTwoHandler.Hello(ctx, in, out)
}
